# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Checked out the commit!

      - name: Deploy to Cloudflare Workers with Wrangler
        # You may pin to the exact commit or the version.
        # uses: cloudflare/wrangler-action@21f14faa062c33c938e3f37c30d52021bed521cb
        uses: cloudflare/wrangler-action@1.2.0
        with:
          # Your Cloudflare API Token
          apiToken: c3AxYwyHv0kYCPL23JDVzS4T4YZDML7XfBLoJ0z9 # optional
#           # The environment you'd like to publish your Workers project to - must be defined in wrangler.toml
#           environment: # optional
#           # The relative path which Wrangler commands should be run from
#           workingDirectory: # optional
#           # The version of Wrangler you'd like to use to publish your Workers project
#           wranglerVersion: # optional
#           # A new line deliminated string of environment variable names that should be configured as Worker secrets
#           secrets: # optional
